apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
  - name: revilo602/meetings-ufe
    newName: revilo602/meetings-ufe
    newTag: 1.2.1 #aktuálna verzia docker obrazu, ktorú chcete aby používatelia - cvičiaci - videli nasadenú
  - name: revilo602/meetings-webapi
    newName: revilo602/meetings-webapi
    newTag: 1.1.0

replacements:
  - targets:
      - select:
          group: fe.milung.eu
          version: v1
          kind: WebComponent
          name: meetings-ufe
        fieldPaths:
          - spec.hash-suffix
    source:
      version: v1
      kind: Deployment
      name: meetings-ufe-deployment
      fieldPath: spec.template.spec.containers.0.image
      options:
        delimiter: ":"
        index: 1
