apiVersion: apps/v1
kind: Deployment
metadata:
  name: meetings-webapi
spec:
  template:
    spec:
      containers:
        - name: openapi-ui
          env:
            - name: URL
              value: /meetings-openapi
            - name: BASE_URL
              value: /meetings-openapi-ui
