kind: Service
apiVersion: v1
metadata:
  name: meetings-openapi-ui
spec:
  selector:
    pod: meetings-webapi-label
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8081
